remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: nump hiren14
description: on tearches day I will teach u guys a numpy 
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
